#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd like this "usr:uid:home"

file="/etc/passwd"

while IFS=":" read -r usr pass gid uid usr_info home cmd_shell ; do
	echo "The user $usr is part of the $gid gang, lives in $home and rides $cmd_shell. $uid's place is protected by the passcode $pass, more info about the user here: $usr_info"
done <$file
