#!/usr/bin/env bash
# this script displays number from 1 to 20. For 4th it displays bad luck from China, for 9th it displays bad luck from Japan and bad luck from Italy for the 17th loop iteration
i="1"
while [ $i -le 20 ]; do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	i=$((i+1))
done
