#!/usr/bin/env bash
# This script displays teh time for 12 hours and 59 minutes
h="0"
while [ $h -le 12 ]; do
	m="1"
	echo "Hour: $h"
	while [ $m -lt 60 ]; do
		echo "$m"
		m=$((m+1))
	done
	h=$((h+1))
done
